# Generated by Django 6.0 on 2025-12-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeInfo',
            fields=[
                ('info_id', models.AutoField(primary_key=True, serialize=False)),
                ('info_content', models.CharField(max_length=200)),
                ('info_creator', models.CharField(max_length=100)),
                ('info_date', models.DateField()),
                ('info_image', models.ImageField(blank=True, null=True, upload_to='knowledge_images/')),
            ],
        ),
    ]
