# Generated by Django 6.0 on 2025-12-23 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0003_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
