# Generated by Django 6.0 on 2026-01-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataapp", "0005_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                ("admin_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=200)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="knowledgeinfo",
            name="info_headline",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="knowledgeinfo",
            name="info_content",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="sci_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="species",
            name="thai_name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
